---
title: "Untitled"
author: "Dina Maulidia Putri"
date: "2026-09-02"
output: html_document
---

```{r}
library(lmtest)
library(orcutt)
```

## Nomer 1

```{r}
data1 <- data.frame(
  Period = 1:20,
  Market_share = c(3.63, 4.20, 3.33, 4.54, 2.89, 4.87, 4.90, 5.29, 6.18, 7.20,
                   7.25, 6.09, 6.80, 8.65, 8.43, 8.29, 7.18, 7.90, 8.45, 8.23),
  Price = c(0.97, 0.95, 0.99, 0.91, 0.98, 0.90, 0.89, 0.86, 0.85, 0.82,
            0.79, 0.83, 0.81, 0.77, 0.76, 0.80, 0.83, 0.79, 0.76, 0.78)
)

# OLS Awal & Uji DW
model1_ols <- lm(Market_share ~ Price, data = data1)
summary(model1_ols)
plot(data1$Period, residuals(model1_ols), type = "b", main = "Residual Data 1")
abline(h = 0, col = "red")
dwtest(model1_ols)

# Penanganan Cochrane-Orcutt
model1_co <- cochrane.orcutt(model1_ols)
summary(model1_co)

# Penanganan Hildreth-Lu
hildreth_lu <- function(y, x, rho) {
  n <- length(y)
  y_star <- y[2:n] - rho * y[1:(n-1)]
  x_star <- x[2:n] - rho * x[1:(n-1)]
  lm(y_star ~ x_star)
}

# Grid search rho Hildreth-Lu Data 1
rhos <- seq(0, 0.99, 0.01)
sses1 <- sapply(rhos, function(r) sum(residuals(hildreth_lu(data1$Market_share, data1$Price, r))^2))
best_rho1 <- rhos[which.min(sses1)]
best_hl1 <- hildreth_lu(data1$Market_share, data1$Price, best_rho1)

best_rho1
summary(best_hl1)
```

## Nomer 2

```{r}
data2 <- data.frame(
  Year = 1975:2014,
  Sales = c(11.7, 12.0, 12.3, 12.8, 13.1, 13.6, 13.9, 14.4, 14.7, 15.3,
            15.5, 15.8, 16.1, 16.6, 16.9, 16.7, 16.9, 17.4, 17.6, 17.9,
            18.0, 17.9, 18.0, 18.2, 18.2, 18.3, 18.6, 19.2, 19.3, 19.5,
            19.2, 19.3, 19.5, 20.0, 20.0, 19.9, 19.8, 19.9, 20.2, 21.0),
  Advertising = c(9.4, 9.6, 10.0, 10.4, 10.8, 10.9, 11.7, 12.2, 12.5, 12.9,
                  13.0, 13.2, 13.8, 14.2, 14.6, 14.4, 15.0, 15.4, 15.7, 15.9,
                  15.9, 16.0, 16.3, 16.2, 16.8, 17.3, 17.6, 18.1, 18.3, 18.5,
                  18.7, 18.9, 19.2, 20.0, 20.0, 20.3, 20.4, 21.0, 21.5, 22.1)
)

# OLS Awal & Uji DW
model2_ols <- lm(Sales ~ Advertising, data = data2)
summary(model2_ols)
plot(data2$Year, residuals(model2_ols), type = "b", main = "Residual Data 2")
abline(h = 0, col = "red")
dwtest(model2_ols)

# Penanganan Cochrane-Orcutt
model2_co <- cochrane.orcutt(model2_ols)
summary(model2_co)

# Grid search rho Hildreth-Lu Data 2
sses2 <- sapply(rhos, function(r) sum(residuals(hildreth_lu(data2$Sales, data2$Advertising, r))^2))
best_rho2 <- rhos[which.min(sses2)]
best_hl2 <- hildreth_lu(data2$Sales, data2$Advertising, best_rho2)

best_rho2
summary(best_hl2)
```

